name       : networkmanager-qt
version    : 5.63.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/networkmanager-qt-5.63.0.tar.xz : 2fd194fa64838dbf419df0a907bac5b1105f29f2261c96de4330283fa3f9ae79
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
