name       : networkmanager-qt
version    : 5.49.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/networkmanager-qt-5.49.0.tar.xz : 5f4c797c5bb2fc73711a91f904702e53f930539b83ed41ab582ceb544569f69a
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
