name       : networkmanager-qt
version    : 5.106.0
release    : 65
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.106/networkmanager-qt-5.106.0.tar.xz : 26abdb7987f2cf15d1f1fa487d10c3d5e96caf0ad6a4e3decb87a1fe4d7b9e1d
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Clause
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.library
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
optimize   : lto
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - network-manager-devel
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
