name       : networkmanager-qt
version    : 5.72.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/networkmanager-qt-5.72.0.tar.xz : e50db6fd656663c19ecfdedc5833acbb21090849ba3b171e57dd0b5a31b04a29
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
