name       : networkmanager-qt
version    : 5.45.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/networkmanager-qt-5.45.0.tar.xz : 803fa6cc0dd9f95a6cda8740617bc6965d88cf506f9abdd35f49882d12fb3702
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
