name       : networkmanager-qt
version    : 5.52.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/networkmanager-qt-5.52.0.tar.xz : 1779ad439c99c5440ac97739fca36c66bb937ee6257a6cabc234c62f9959bd5e
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
