name       : networkmanager-qt
version    : 5.35.0
release    : 2
source     :
    - https://download.kde.org/stable/frameworks/5.35/networkmanager-qt-5.35.0.tar.xz : 20622cb737e82724ec80ec1bb0b7e121754f88ff78904777d41a4b826524bd37
license    : LGPL-2.1
component  : desktop.library
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
