name       : networkmanager-qt
version    : 5.67.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/networkmanager-qt-5.67.0.tar.xz : 6c6927765daf4a9cba1aac0b2fed9e8cca1c5c1a181f895b27cb860b2dbb63ae
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
