name       : networkmanager-qt
version    : 5.32.0
release    : 1
source     :
    - https://download.kde.org/stable/frameworks/5.32/networkmanager-qt-5.32.0.tar.xz : cde39ee19c832ddda73d8e1f6f636b726104accc95ce3e07545df4edbe3d9e2d
license    : LGPL-2.1
component  : desktop.library
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
