name       : networkmanager-qt
version    : 5.51.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/networkmanager-qt-5.51.0.tar.xz : bd6d64b928e46fd257b36b756655fb9850ed98c20247abee3c6b23559f913a96
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
