name       : networkmanager-qt
version    : 5.75.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/networkmanager-qt-5.75.0.tar.xz : ba9d15eb5e0e624ffaac591cdaad43dc62e60ccfa25b98be686b58800b41018b
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Clause
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
