name       : networkmanager-qt
version    : 5.89.0
release    : 54
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.89/networkmanager-qt-5.89.0.tar.xz : 045fd1fa88c6d187f75569bb145240d6da92a47839f96ae40210d5469cee37f4
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Clause
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.library
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
optimize   : lto
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
