name       : networkmanager-qt
version    : 5.79.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/networkmanager-qt-5.79.0.tar.xz : da54339c4a8946bf430b01d7ec53542d1d6aab816a01303ad3fb8f8385c22a12
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Clause
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.library
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
optimize   : lto
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
