name       : networkmanager-qt
version    : 5.46.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/networkmanager-qt-5.46.0.tar.xz : f6fef99a17056542a24a4b41e9047eaee626d6616cc489a3304d3a73eed3e5de
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
