name       : networkmanager-qt
version    : 5.60.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/networkmanager-qt-5.60.0.tar.xz : fae1d2e36e0c79095cfa3d907c86c47272226a6952ab93139b750f29e9215a65
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
