name       : networkmanager-qt
version    : 5.47.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/networkmanager-qt-5.47.0.tar.xz : d0b377500ee4cf4f029f4d04d6844bcf3d2d6734982b511a5fffab5165688209
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
