name       : networkmanager-qt
version    : 5.68.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/networkmanager-qt-5.68.0.tar.xz : 6a9bea5e6d58f5322848114e4e827edadee6b5a890a3549446ff23a568325e2c
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
