name       : networkmanager-qt
version    : 5.36.0
release    : 3
source     :
    - https://download.kde.org/stable/frameworks/5.36/networkmanager-qt-5.36.0.tar.xz : 5d2845ea6b25e1c73f6ce2b9236a3ceccf3271c4d18f67fa917cee13154e31d6
license    : LGPL-2.1
component  : desktop.library
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
builddeps  :
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
