name       : networkmanager-qt
version    : 5.83.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/networkmanager-qt-5.83.0.tar.xz : 618fd7e68438dce44b287a3b46c790853604f65017b84fcebbf4eb31b443686d
homepage   : https://community.kde.org/Frameworks
license    :
    - BSd-3-Clause
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.library
summary    : Qt wrapper for NetworkManager DBus API
description: |
    NetworkManagerQt provides access to all NetworkManager features exposed on DBus. It allows you to manage your connections and control your network devices and also provides a library for parsing connection settings which are used in DBus communication.
optimize   : lto
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
